//Auth
export const GENERATEOTP_REQUESTED = "GENERATEOTP_REQUESTED";
export const GENERATEOTP_SUCCESS = "GENERATEOTP_SUCCESS";
export const GENERATEOTP_FAILED = "GENERATEOTP_FAILED";
export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

//SURVEY
export const FETCH_SURVEY_REQUESTED = "FETCH_SURVEY_REQUESTED";
export const FETCH_SURVEY_SUCCESS = "FETCH_SURVEY_SUCCESS";
export const FETCH_SURVEY_FAILED = "FETCH_SURVEY_FAILED";

export const SAVE_SURVEY_REQUESTED = "SAVE_SURVEY_REQUESTED";
export const SAVE_SURVEY_SUCCESS = "SAVE_SURVEY_SUCCESS";
export const SAVE_SURVEY_FAILED = "SAVE_SURVEY_FAILED";

export const GET_SURVEYLIST_REQUESTED = "GET_SURVEYLST_FREQUESTED";
export const GET_SURVEYLIST_SUCCESS = "GET_SURVEYLIST_SUCCESS";
export const GET_SURVEYLIST_FAILED = "GET_SURVEYLIST_FAILED";
