//Auth
export const GENERATEOTP_REQUESTED = "GENERATEOTP_REQUESTED";
export const GENERATEOTP_SUCCESS = "GENERATEOTP_SUCCESS";
export const GENERATEOTP_FAILED = "GENERATEOTP_FAILED";
export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
